# coding: utf-8

"""
    Factern API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import factern_client
from factern_client.com.factern.model.label_list_node import LabelListNode  # noqa: E501
from factern_client.rest import ApiException


class TestLabelListNode(unittest.TestCase):
    """LabelListNode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLabelListNode(self):
        """Test LabelListNode"""
        # FIXME: construct object with mandatory attributes with example values
        # model = factern_client.models.label_list_node.LabelListNode()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
