# coding: utf-8

"""
    Factern API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import factern_client
from factern_client.com.factern.model.create_field_response import CreateFieldResponse  # noqa: E501
from factern_client.rest import ApiException


class TestCreateFieldResponse(unittest.TestCase):
    """CreateFieldResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateFieldResponse(self):
        """Test CreateFieldResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = factern_client.models.create_field_response.CreateFieldResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
