# coding: utf-8

"""
    Factern API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import factern_client
from factern_client.com.factern.model.add_statement_response import AddStatementResponse  # noqa: E501
from factern_client.rest import ApiException


class TestAddStatementResponse(unittest.TestCase):
    """AddStatementResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAddStatementResponse(self):
        """Test AddStatementResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = factern_client.models.add_statement_response.AddStatementResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
