# coding: utf-8

"""
    Factern API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import factern_client
from factern_client.com.factern.model.create_child_request import CreateChildRequest  # noqa: E501
from factern_client.rest import ApiException


class TestCreateChildRequest(unittest.TestCase):
    """CreateChildRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateChildRequest(self):
        """Test CreateChildRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = factern_client.models.create_child_request.CreateChildRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
