# coding: utf-8

"""
    Factern API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import factern_client
from factern_client.com.factern.model.statement import Statement  # noqa: E501
from factern_client.rest import ApiException


class TestStatement(unittest.TestCase):
    """Statement unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStatement(self):
        """Test Statement"""
        # FIXME: construct object with mandatory attributes with example values
        # model = factern_client.models.statement.Statement()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
