# coding: utf-8

"""
    Factern API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import factern_client
from factern_client.com.factern.model.bid_node import BidNode  # noqa: E501
from factern_client.rest import ApiException


class TestBidNode(unittest.TestCase):
    """BidNode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBidNode(self):
        """Test BidNode"""
        # FIXME: construct object with mandatory attributes with example values
        # model = factern_client.models.bid_node.BidNode()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
