language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
install: pip install -r requirements.txt
script: pytest
deploy:
  provider: pypi
  skip_existing: true
  user: factern
  password:
    secure: eFbfk3GC7hboBSegCxWKv/7iQWs7kp4WdiuiVEoGfqmpbjVcELNigQ4zIOOztIEctMhrermdiayyjrGe608H+qL4Biajbt9ZrE76DIn23KSueVtPomweWidQ4gJ0TCBsgrXdESLtR0vGj3FHJO5rBMgx3sbgYxqPs9ABNJp/Mtjr110/7fkoU/9kJVXhh5sYIgWdwtmZ45oMx9u+OygGwbCb8vZHVTbSSVTFJu6P6No98OHpIUxKvwNauwBB7RJReW8n75veIZYkFZlOWA/ncaqXPCZW4Z703048USDpNYxNFtX+kIu0eqhnDcEyuZsNnevSdGfaTWHcomRWAy73uTPre+z8gdHAVaK7ZPqc1FaWx8w1/V8EZniU8jIOYFYsGXV6V1zEoC6tEw+7Whjc1jv4OCaFY9q4n5WrbPHDgHGisePiPlm8obsjNr+UVDXwPaWri37pWt5Kuuad4RgIOaxi24rbVN6ckmyt0O8yiE2KpLufbxJJmIEJiZqMT7KPLpZrSga86xwv4AUoWJ5cOqNNjmWYlsojogYynoaWdkkbhAiGObm1XSCb1zcUf8HOW7CxUsJjcbX7TBslVk32uBu9SJgxnX5B5/WKfZIMEL58FGbRKvxYmE4V5irDPGDaPO5NWUH434yNRTw05jGofWLbctZW8C9CRyI7qd2cdzo=
  on:
    tag: true
    branch: master
    repo: Factern/factern-client-python
