language: python
python:
- '2.7'
- '3.2'
- '3.3'
- '3.4'
- '3.5'
install: pip install -r requirements.txt
script: tox
env:
  FACTERN_CLIENT_SECRET:
    secure: gs/Mmrk4JYtASKqxGA4zyBo86sdrA7BDCuiN8pS4v/3NLZpu5Fum8P2EXozlH3YgtxWCgJjq9m1zUrkifpSf6oBTCiSWOEQmn3l5aU1WXwx7xv+rx1FtPOY3Z2fxwSdH0YElqmb2AfPiWGahRTivEn+rf2XuWUWQXxSd+XMWWd+5x8XIQepUbkTFz70Jc1CSeeD59AmFIJcE0K8n3dMyi1+nVW+UtiKnXCvd6lHPtz7SZPWT1QpGzul2Er9z5Dem6PxbrqGUjtskOJtWGvIejuchRt3AJmBqCvEckYu/KLXsmF5ucvvsUt4bAxiVIJqyCT6oGPi2PfRVIUmYqj2zyhMn0cr+9umBHe7ccgR2ZU28M+IIwWVYECELZSv4RxTHpWkvWeaSHv+19ChpUkAciJSlsLEwZjrLTduyoFUQ5LnAlfJ6qMhmfZh45GpngBXzHauepah9J0JhHl+9CG4Ykh/QC1Kf7XDZP26TIvTDUIg9seP+fSzB5byZaVDuUe5+GJm2WcTwnhCXKOaLPyckVWbtUAx+xyXO0TufHvwlFz9X8UHgklfsodl0pYE1Za4MXzocslkjbMgX5sxxpdWwakc90bGQU0kFJiKrMbDxRmB/yBbBC1OxUqxz0mGFEqxHgB6+DEdEnfKoW0IvVMz3PLzu98LMfHqyCtuzyr+8sZI=
